version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: brainboo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: brainboo-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin  # Set your own username
      - ME_CONFIG_BASICAUTH_PASSWORD=pass123
    depends_on:
      - mongo


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainboo-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/brainboo
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: local.Dockerfile
    container_name: brainboo-frontend
    restart: always
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
  node_modules:
