// frontend/constants.js
export const majors = [
  "Applied Computing",
  "Cybersecurity",
  "Data Science",
  "Information Systems",
  "Information Technology",
  "Computer Science"
];

export const topics = [
  "Machine Learning",
  "Artificial Intelligence",
  "Data Analytics",
  "Cybersecurity Fundamentals",
  "Network Security",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Internet of Things (IoT)",
  "Big Data",
  "Data Mining",
  "Data Visualization",
  "Database Management",
  "Software Engineering",
  "Algorithms and Data Structures",
  "Operating Systems",
  "Computer Networks",
  "Information Systems Management",
  "Digital Forensics",
  "Cryptography",
  "Ethical Hacking",
  "Blockchain",
  "DevOps",
  "Virtualization",
  "Software Testing",
  "UI/UX Design",
  "Human-Computer Interaction",
  "Computer Graphics",
  "Game Development",
  "Natural Language Processing",
  "Robotics",
  "Automation",
  "Augmented Reality",
  "Virtual Reality",
  "Bioinformatics",
  "E-commerce",
  "IT Project Management",
  "Systems Analysis",
  "Business Intelligence",
  "Predictive Analytics",
  "Deep Learning",
  "Neural Networks",
  "Statistical Analysis",
  "Geospatial Analysis",
  "Digital Marketing",
  "IT Compliance",
  "Software Architecture",
  "Mobile Security",
  "Network Administration",
  "IT Governance"
];
